language: r
cache: packages
sudo: true

r:
#  - oldrel
  - release
  - devel


warnings_are_errors: true

notifications:
  slack:
    rooms:
    
    on_success: change # default: always
    on_failure: always # default: always
